-- Each section is prefixed by a descriptor that indicates how the data should be parsed once generated
-- table: indicates rows should be treated as-is
-- serialized: indicates each row consists of a single field that has been generated by php#s serialize function
-- total: indicates each row contains a single field representing a number that should be totaled

select "__table:system__" as ``;
--  All modules available and status
select name, status from system;

-- Entity list
select "__table:entities__" as ``;
select entity, bundle from scratchpads_statistics_entity_bundle;

-- All nodes
select "__table:nodes__" as ``;
select type, count(*) as count from node where status>0 group by type;

-- Entity/bundle fields
select "__table:fields__" as '';
select field_name, entity_type, bundle from field_config_instance where field_id>0;

select "__serialized:vids.biological__" as ``;
select value from variable where name like "biological_vids";

select "__serialized:vids.nonbiological__" as ``;
select value from variable where name like "none_biological_vids";

select "__table:taxonomy_terms__" as '';
select t.name, t.machine_name, t.vid, count(*) as total from taxonomy_term_data as d left join taxonomy_vocabulary as t on(t.vid=d.vid) group by vid;

--  bhl: created dates
select "__table:bhl__" as ``;
select created from cache_bhl;

--  biography
--  To count users that have filled in any of the extra fields:
select "__total:biography.data__" as ``;
select count(*) from (select entity_id from field_data_field_alternative_name
	union select entity_id from field_data_field_areas_of_professional_inte
	union select entity_id from field_data_field_biography
	union select entity_id from field_data_field_birth_date
	union select entity_id from field_data_field_birth_place
	union select entity_id from field_data_field_comments
	union select entity_id from field_data_field_death_date
	union select entity_id from field_data_field_example_of_handwriting
	union select entity_id from field_data_field_gender
	union select entity_id from field_data_field_known_for
	union select entity_id from field_data_field_main_collaborators_co_auth
	union select entity_id from field_data_field_make_this_profile_public_
	union select entity_id from field_data_field_orcid
	union select entity_id from field_data_field_places_worked
	union select entity_id from field_data_field_related_links
	union select entity_id from field_data_field_standard_form
	union select entity_id from field_data_field_user_keywords) as t1;

select "__total:biography.public__" as ``;
--  To count only users who have made their profiles public:
select count(*) from field_data_field_make_this_profile_public_ where field_make_this_profile_public__value=1;

--  Blogs created & updated dates
select "__table:blog__" as ``;
select created, changed from node where type='blog';

-- Number of views with charts
select "__total:charts__" as ``;
select count(*) from views_display where display_options like '%"style_plugin";s:6:"charts"%';

-- Language, status, created and changed dates of translated content
select "__table:translation__" as ``;
select language, status, created, changed from entity_translation;

-- Number of contexts created
select "__total:contexts__" as ``;
select count(*) from context;

-- Number of type, status, created and changed dates of darwincore nodes
select "__table:dwc__" as ``;
select type, status, created, changed from node where type in ('location', 'specimen_observation');

-- Number of dwcarchives
select "__total:dwcarchiver__" as ``;
select count(*) from dwcarchiver_archive;

-- Ecoint nodes
select "__table:ecoint__" as ``;
select status, created, changed from node where type='ecological_interactions';

-- Eolapi searches: created, changed dates
select "__table:eolapi__" as ``;
select created, changed from eolapi where type='search';

-- Event nodes
select "__table:event__" as ``;
select status, created, changed from node where type='event';

-- Exif
select "__total:exif.mappings__" as ``;
-- Number of field mappings
select count(*) from exif_custom_maps as e left join exif_custom_mapped_fields as f on(f.mid = e.mid) where img_field != '0';

select "__total:exif.default__" as ``;
-- Is global default set?
select count(*) from variable where name like 'exif_custom_default';

select "__total:exif.users__" as ``;
-- Number of user settings
select count(*) from exif_custom_users;

-- Forum topics creation date, last comment date, number of comments
select "__table:forum__" as ``;
select created, last_comment_timestamp, comment_count from forum_index;

-- Number of gbif map layers
select "__total:gbifmap__" as ``;
select count(*) from eol_gbif_maps_tid_map;

-- Is the site registered with gbif?
select "__total:gbifclient__" as ``;
select count(*) from variable where name like 'scratchpads_gbif_registry_client_uuid';

-- Number of groups
select "__table:groups__" as ``;
select state, created from og;

-- Group content including entity, group id, state, created date
select "__table:groupcontent__" as ``;
select entity_type, gid, state, created from og_membership;

-- IUCN taxon results: creation date and status (1=no data)
select "__table:iucn__" as ``;
select created, data like 'The IUCN does not hold any information for%' as no_data from cache_iucn;

-- Lexicon: Number of vocabularies used as lexicons
select "__serialized:lexicon__" as ``;
select value from variable where name like 'lexicon_vids';

-- Lucid: Number of lucid archives
select "__serialized:lucid__" as ``;
select value from variable where name like 'scratchpads_lucid_archives';

-- NCBI: Created dates of linked taxa
select "__table:ncbi__" as ``;
select created from cache_ncbi;

-- Newsletter
select "__total:newsletter.categories__" as ``;
-- Number of categories
select count(*) from simplenews_category;

select "__table:newsletter.subscribers__" as ``;
-- Created dates
select created from simplenews_subscriber;

select "__table:newsletter.nodes__" as ``;
-- Nodes
select status, created, changed from node where type = 'simplenews';

-- Pensoft publications
select "__table:pensoft__" as ``;
select created, changed, status, published from publication;

-- ReFindIt created dates of linked taxa
select "__table:refindit__" as ``;
select created from cache_refindit;

-- Rules: Status and count of rules configs
select "__table:rules__" as ``;
select status, count(*) as count from rules_config group by status;

-- UI Translate: Language and number of translations
select "__table:translateui__" as ``;
select language, count(*) as count from locales_target group by language;

-- Views: Number of custom views
select "__total:views__" as ``;
select count(*) from views_view;

-- Webforms
select "__table:webforms.nodes__" as ``;
-- Nodes
select created, changed, status from node where type='webform';

select "__table:webforms.submissions__" as ``;
-- Submissions draft status & submitted date
select is_draft, submitted from webform_submissions;

-- Worms - number of linked taxa
select "__total:worms__" as ``;
select count(*) from worms;

-- Recently created/edited content
select "__table:recent.taxonomy__" as ``;
select t.tid, t.uid, t.timestamp, users.name from taxonomy_term_data_revision as t left join users on(t.uid=users.uid) where timestamp > unix_timestamp(now()-interval 3 month);

select "__table:recent.changednodes__" as ``;
select n.nid, n.uid, n.created, n.changed, u.name, n.type from node as n left join users as u on(n.uid=u.uid) where (n.created > unix_timestamp(now()-interval 3 month)) or (n.changed > unix_timestamp(now()-interval 3 month));
