-- Each section is prefixed by a descriptor that indicates how the data should be parsed once generated
-- table: indicates rows should be treated as-is
-- serialized: indicates each row consists of a single field that has been generated by php#s serialize function
-- total: indicates each row contains a single field representing a number that should be totaled

select "__table:system__" as ``;
--  All modules available and status
select name, status from system;

-- Entity list
select "__table:entities__" as ``;
select entity, bundle from scratchpads_statistics_entity_bundle;

-- All nodes
select "__table:nodes__" as ``;
select type, count(*) as count from node where status>0 group by type;

-- Entity/bundle fields
select "__table:fields__" as '';
select field_name, entity_type, bundle from field_config_instance where field_id>0 and deleted=0;

select "__serialized:vids.biological__" as ``;
select value from variable where name like "biological_vids";

select "__serialized:vids.nonbiological__" as ``;
select value from variable where name like "none_biological_vids";

select "__table:taxonomy_terms__" as '';
select t.name, t.machine_name, t.vid, count(*) as total from taxonomy_term_data as d left join taxonomy_vocabulary as t on(t.vid=d.vid) group by vid;

-- Recently created/edited content
select "__table:recent.taxonomy__" as ``;
select t.tid, t.uid, t.timestamp, users.name from taxonomy_term_data_revision as t left join users on(t.uid=users.uid) where timestamp > unix_timestamp(now()-interval 3 month);

select "__table:recent.changednodes__" as ``;
select n.nid, n.uid, n.created, n.changed, u.name, n.type from node as n left join users as u on(n.uid=u.uid) where (n.created > unix_timestamp(now()-interval 3 month)) or (n.changed > unix_timestamp(now()-interval 3 month));

-- Biblio usage data
select "__table:biblio.types__" as ``;
select distinct biblio_type, name from biblio left join biblio_types on (biblio.biblio_type=biblio_types.tid);

select * from (
select "biblio_number" as name, count(*) from biblio where biblio_number is not null
union
select "biblio_other_number" as name, count(*) from biblio where biblio_other_number is not null
union
select "biblio_sort_title" as name, count(*) from biblio where biblio_sort_title is not null
union
select "biblio_secondary_title" as name, count(*) from biblio where biblio_secondary_title is not null
union
select "biblio_tertiary_title" as name, count(*) from biblio where biblio_tertiary_title is not null
union
select "biblio_edition" as name, count(*) from biblio where biblio_edition is not null
union
select "biblio_publisher" as name, count(*) from biblio where biblio_publisher is not null
union
select "biblio_place_published" as name, count(*) from biblio where biblio_place_published is not null
union
select "biblio_year" as name, count(*) from biblio where biblio_year is not null
union
select "biblio_volume" as name, count(*) from biblio where biblio_volume is not null
union
select "biblio_pages" as name, count(*) from biblio where biblio_pages is not null
union
select "biblio_date" as name, count(*) from biblio where biblio_date is not null
union
select "biblio_isbn" as name, count(*) from biblio where biblio_isbn is not null
union
select "biblio_lang" as name, count(*) from biblio where biblio_lang is not null
union
select "biblio_abst_e" as name, count(*) from biblio where biblio_abst_e is not null
union
select "biblio_abst_f" as name, count(*) from biblio where biblio_abst_f is not null
union
select "biblio_full_text" as name, count(*) from biblio where biblio_full_text is not null
union
select "biblio_url" as name, count(*) from biblio where biblio_url is not null
union
select "biblio_issue" as name, count(*) from biblio where biblio_issue is not null
union
select "biblio_type_of_work" as name, count(*) from biblio where biblio_type_of_work is not null
union
select "biblio_accession_number" as name, count(*) from biblio where biblio_accession_number is not null
union
select "biblio_call_number" as name, count(*) from biblio where biblio_call_number is not null
union
select "biblio_notes" as name, count(*) from biblio where biblio_notes is not null
union
select "biblio_custom1" as name, count(*) from biblio where biblio_custom1 is not null
union
select "biblio_custom2" as name, count(*) from biblio where biblio_custom2 is not null
union
select "biblio_custom3" as name, count(*) from biblio where biblio_custom3 is not null
union
select "biblio_custom4" as name, count(*) from biblio where biblio_custom4 is not null
union
select "biblio_custom5" as name, count(*) from biblio where biblio_custom5 is not null
union
select "biblio_custom6" as name, count(*) from biblio where biblio_custom6 is not null
union
select "biblio_custom7" as name, count(*) from biblio where biblio_custom7 is not null
union
select "biblio_research_notes" as name, count(*) from biblio where biblio_research_notes is not null
union
select "biblio_number_of_volumes" as name, count(*) from biblio where biblio_number_of_volumes is not null
union
select "biblio_short_title" as name, count(*) from biblio where biblio_short_title is not null
union
select "biblio_alternate_title" as name, count(*) from biblio where biblio_alternate_title is not null
union
select "biblio_original_publication" as name, count(*) from biblio where biblio_original_publication is not null
union
select "biblio_reprint_edition" as name, count(*) from biblio where biblio_reprint_edition is not null
union
select "biblio_translated_title" as name, count(*) from biblio where biblio_translated_title is not null
union
select "biblio_section" as name, count(*) from biblio where biblio_section is not null
union
select "biblio_citekey" as name, count(*) from biblio where biblio_citekey is not null
union
select "biblio_coins" as name, count(*) from biblio where biblio_coins is not null
union
select "biblio_doi" as name, count(*) from biblio where biblio_doi is not null
union
select "biblio_issn" as name, count(*) from biblio where biblio_issn is not null
union
select "biblio_auth_address" as name, count(*) from biblio where biblio_auth_address is not null
union
select "biblio_remote_db_name" as name, count(*) from biblio where biblio_remote_db_name is not null
union
select "biblio_remote_db_provider" as name, count(*) from biblio where biblio_remote_db_provider is not null
union
select "biblio_label" as name, count(*) from biblio where biblio_label is not null
union
select "biblio_access_date" as name, count(*) from biblio where biblio_access_date is not null
union
select "biblio_refereed" as name, count(*) from biblio where biblio_refereed is not null
union
select "biblio_md5" as name, c
select * from (
select "biblio_number" as name, count(*) from biblio where biblio_number is not null
union
select "biblio_other_number" as name, count(*) from biblio where biblio_other_number is not null
union
select "biblio_sort_title" as name, count(*) from biblio where biblio_sort_title is not null
union
select "biblio_secondary_title" as name, count(*) from biblio where biblio_secondary_title is not null
union
select "biblio_tertiary_title" as name, count(*) from biblio where biblio_tertiary_title is not null
union
select "biblio_edition" as name, count(*) from biblio where biblio_edition is not null
union
select "biblio_publisher" as name, count(*) from biblio where biblio_publisher is not null
union
select "biblio_place_published" as name, count(*) from biblio where biblio_place_published is not null
union
select "biblio_year" as name, count(*) from biblio where biblio_year is not null
union
select "biblio_volume" as name, count(*) from biblio where biblio_volume is not null
union
select "biblio_pages" as name, count(*) from biblio where biblio_pages is not null
union
select "biblio_date" as name, count(*) from biblio where biblio_date is not null
union
select "biblio_isbn" as name, count(*) from biblio where biblio_isbn is not null
union
select "biblio_lang" as name, count(*) from biblio where biblio_lang is not null
union
select "biblio_abst_e" as name, count(*) from biblio where biblio_abst_e is not null
union
select "biblio_abst_f" as name, count(*) from biblio where biblio_abst_f is not null
union
select "biblio_full_text" as name, count(*) from biblio where biblio_full_text is not null
union
select "biblio_url" as name, count(*) from biblio where biblio_url is not null
union
select "biblio_issue" as name, count(*) from biblio where biblio_issue is not null
union
select "biblio_type_of_work" as name, count(*) from biblio where biblio_type_of_work is not null
union
select "biblio_accession_number" as name, count(*) from biblio where biblio_accession_number is not null
union
select "biblio_call_number" as name, count(*) from biblio where biblio_call_number is not null
union
select "biblio_notes" as name, count(*) from biblio where biblio_notes is not null
union
select "biblio_custom1" as name, count(*) from biblio where biblio_custom1 is not null
union
select "biblio_custom2" as name, count(*) from biblio where biblio_custom2 is not null
union
select "biblio_custom3" as name, count(*) from biblio where biblio_custom3 is not null
union
select "biblio_custom4" as name, count(*) from biblio where biblio_custom4 is not null
union
select "biblio_custom5" as name, count(*) from biblio where biblio_custom5 is not null
union
select "biblio_custom6" as name, count(*) from biblio where biblio_custom6 is not null
union
select "biblio_custom7" as name, count(*) from biblio where biblio_custom7 is not null
union
select "biblio_research_notes" as name, count(*) from biblio where biblio_research_notes is not null
union
select "biblio_number_of_volumes" as name, count(*) from biblio where biblio_number_of_volumes is not null
union
select "biblio_short_title" as name, count(*) from biblio where biblio_short_title is not null
union
select "biblio_alternate_title" as name, count(*) from biblio where biblio_alternate_title is not null
union
select "biblio_original_publication" as name, count(*) from biblio where biblio_original_publication is not null
union
select "biblio_reprint_edition" as name, count(*) from biblio where biblio_reprint_edition is not null
union
select "biblio_translated_title" as name, count(*) from biblio where biblio_translated_title is not null
union
select "biblio_section" as name, count(*) from biblio where biblio_section is not null
union
select "biblio_citekey" as name, count(*) from biblio where biblio_citekey is not null
union
select "biblio_coins" as name, count(*) from biblio where biblio_coins is not null
union
select "biblio_doi" as name, count(*) from biblio where biblio_doi is not null
union
select "biblio_issn" as name, count(*) from biblio where biblio_issn is not null
union
select "biblio_auth_address" as name, count(*) from biblio where biblio_auth_address is not null
union
select "biblio_remote_db_name" as name, count(*) from biblio where biblio_remote_db_name is not null
union
select "biblio_remote_db_provider" as name, count(*) from biblio where biblio_remote_db_provider is not null
union
select "biblio_label" as name, count(*) from biblio where biblio_label is not null
union
select "biblio_access_date" as name, count(*) from biblio where biblio_access_date is not null
union
select "biblio_refereed" as name, count(*) from biblio where biblio_refereed is not null
union
select "biblio_md5" as name, count(*) from biblio where biblio_md5 is not null
union
select "biblio_formats" as name, count(*) from biblio where biblio_formats is not null)ount(*) from biblio where biblio_md5 is not null
union
select "biblio_formats" as name, count(*) from biblio where biblio_formats is not null) as t1
