-- Each section is prefixed by a descriptor that indicates how the data should be parsed once generated
-- table: indicates rows should be treated as-is
-- serialized: indicates each row consists of a single field that has been generated by php#s serialize function
-- total: indicates each row contains a single field representing a number that should be totaled

select "__table:system__" as ``;
--  All modules available and status
select name, status from system;

-- Entity list
select "__table:entities__" as ``;
select entity, bundle from scratchpads_statistics_entity_bundle;

-- All nodes
select "__table:nodes__" as ``;
select type, count(*) as count from node where status>0 group by type;

-- Entity/bundle fields
select "__table:fields__" as '';
select field_name, entity_type, bundle from field_config_instance where field_id>0 and deleted=0;

select "__serialized:vids.biological__" as ``;
select value from variable where name like "biological_vids";

select "__serialized:vids.nonbiological__" as ``;
select value from variable where name like "none_biological_vids";

select "__table:taxonomy_terms__" as '';
select t.name, t.machine_name, t.vid, count(*) as total from taxonomy_term_data as d left join taxonomy_vocabulary as t on(t.vid=d.vid) group by vid;

-- Recently created/edited content
select "__table:recent.taxonomy__" as ``;
select t.tid, t.uid, t.timestamp, users.name from taxonomy_term_data_revision as t left join users on(t.uid=users.uid) where timestamp > unix_timestamp(now()-interval 3 month);

select "__table:recent.changednodes__" as ``;
select n.nid, n.uid, n.created, n.changed, u.name, n.type from node as n left join users as u on(n.uid=u.uid) where (n.created > unix_timestamp(now()-interval 3 month)) or (n.changed > unix_timestamp(now()-interval 3 month));
